### ISSUE TITLE
If Janus server is restarted, LongPoll errors and loops

### ISSUE THREAD

**Issue by Misterblue** [Misterblue/os-webrtc-janus#8]
The LongPoll does not survive the restarting of the Janus server. Note that it gets a 404 probably because the restarted Janus server has a different session number.
Need some code to handle the reconnection.

2024-12-09 18:51:04,039 ERROR [JANUS SESSION] EventLongPoll: exception System.NullReferenceException: Object reference not set to an instance of an object.
   at WebRtcVoice.JanusSession.<StartLongPoll>b__69_0() in /home/opensim/opensim/addon-modules/os-webrtc-janus/Janus/JanusSession.cs:line 496
2024-12-09 18:51:04,038 ERROR [JANUS SESSION] GetFromJanus: response not successful StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: Keep-Alive
  Access-Control-Max-Age: 86400
  Access-Control-Allow-Origin: *
  Date: Mon, 09 Dec 2024 18:51:04 GMT
  Content-Length: 0
}
2024-12-09 18:51:04,041 ERROR [JANUS SESSION] EventLongPoll: exception System.NullReferenceException: Object reference not set to an instance of an object.
   at WebRtcVoice.JanusSession.<StartLongPoll>b__69_0() in /home/opensim/opensim/addon-modules/os-webrtc-janus/Janus/JanusSession.cs:line 496
2024-12-09 18:51:04,044 ERROR [JANUS SESSION] GetFromJanus: response not successful StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: Keep-Alive
  Access-Control-Max-Age: 86400
  Access-Control-Allow-Origin: *
  Date: Mon, 09 Dec 2024 18:51:04 GMT
  Content-Length: 0
}
2024-12-09 18:51:04,047 ERROR [JANUS SESSION] EventLongPoll: exception System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by Misterblue** [comment]
Added catch in LongPoll code and return error to shutdown session on OnDisconnect event.

FS retries and things recover if Janus is stopped and restarted.

Fixed in 1.0.11.
